CREATE TABLE TEACHER
(
	"TID" NVARCHAR(15)NOT NULL,
	"FNAME" NVARCHAR(10)NOT NULL,
	"MNAME"	NVARCHAR(10),
	"LNAME" NVARCHAR(10),
	PRIMARY KEY(TID)	
);
CREATE TABLE SUB
(
	"SUB_ID" NVARCHAR(10)NOT NULL,
	"NAME" NVARCHAR(20)NOT NULL,
	PRIMARY KEY(SUB_ID)
);
CREATE TABLE CLASS
(
	"CLASS_ID" NVARCHAR(10)NOT NULL,
	"BATCH" DATE NOT NULL,
	PRIMARY KEY(CLASS_ID)
);
CREATE TABLE ASSIGNEDTEACHER
(
	"CLASS_ID" NVARCHAR(10) REFERENCES CLASS("CLASS_ID"),
	"SUB_ID" NVARCHAR(10) REFERENCES SUB("SUB_ID"),
	"TID" NVARCHAR(15) REFERENCES TEACHER("TID")
);
CREATE TABLE STUDENT
(
	"SID" NVARCHAR(14) NOT NULL,
	"SFNAME" NVARCHAR(10) NOT NULL,
	"MNAME"  NVARCHAR(10),
	"LNAME"  NVARCHAR(10) NOT NULL,
	"CLASS_ID" NVARCHAR(10) REFERENCES CLASS(CLASS_ID)
	PRIMARY KEY(SID)
);
CREATE TABLE PROGRAM
(
	"SID" NVARCHAR(14) REFERENCES STUDENT("SID"),
	"PID" INT NOT NULL,
	"DATE" DATE NOT NULL,
	"GROUP" NVARCHAR(14) NOT NULL,
	"Description" NVARCHAR(100) NOT NULL,
	"SUB_ID" NVARCHAR(10) REFERENCES SUB("SUB_ID"),
	PRIMARY KEY(PID) 
);